apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: registry-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.kubernetes.io/rewrite-target: /
    #traefik.ingress.kubernetes.io/service.serversscheme: https
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - registry.mycluster.tld
    - secretName: registry-ingress-tls
  rules:
    - host: registry.mycluster.tld
      http:
        paths:
          - backend:
              serviceName: image-registry
              servicePort: 443 # has to be 443 for docker push ending up with TLS at registry container
            path: /