kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: registry-ns
  labels:
    app: docker-registry
spec:
  type: LoadBalancer
  selector:
    app: docker-registry
  ports:
    - name: http
      port: 5000
      #targetPort: 5000
