apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: registry-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry-container
          image: registry:2
          env:
            - name: REGISTRY_HTTP_ADDR
              value: ":5000"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
            ## TLS (might be terminated at ingress controller)
            #- name: REGISTRY_HTTP_TLS_CERTIFICATE
            #  value: /cert/tls.crt
            #- name: REGISTRY_HTTP_TLS_KEY
            #  value: /cert/tls.key
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: image-store-volume
              mountPath: /var/lib/registry
            ## TLS (might be terminated at ingress controller)
            #- name: registry-cert-volume
            #  mountPath: /cert/
            #  readOnly: true
      volumes:
        - name: image-store-volume
          emptyDir: {}
        ## TLS (might be terminated at ingress controller)
        #- name: registry-cert-volume
        #  secret:
        #    secretName: docker-registry-tls
        #    #secretName: selfsigned-cert


