apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  labels:
    app: whoami-service
spec:
  selector:
    app: whoami-service
  ports:
  - name: http
    targetPort: 80
    port: 8888
  selector:
    app: whoami
  type: LoadBalancer
